requires 'AnyEvent::Curl::Multi';
requires 'App::Prove';
requires 'CPAN::Meta::Requirements';
requires 'Captcha::reCAPTCHA', '0.94';
requires 'Catalyst', '5.90053';
requires 'Catalyst::Action::RenderView';
requires 'Catalyst::Authentication::Store::Proxy', '0.0.1';
requires 'Catalyst::Authentication::User';
requires 'Catalyst::Controller::ActionRole';
requires 'Catalyst::Model';
requires 'Catalyst::Plugin::Authentication';
requires 'Catalyst::Plugin::ConfigLoader';
requires 'Catalyst::Plugin::Static::Simple';
requires 'Catalyst::Plugin::Unicode::Encoding';
requires 'Catalyst::TraitFor::Request::REST::ForBrowsers';
requires 'Catalyst::View::JSON';
requires 'Catalyst::View::TT::Alloy';
requires 'CatalystX::RoleApplicator';
requires 'Config::General';
requires 'CPAN::Changes', '0.21';
requires 'Data::Dumper';
requires 'DateTime';
requires 'DateTime::Format::HTTP';
requires 'DateTime::Format::ISO8601';
requires 'Digest::MD5';
requires 'Digest::SHA1';
requires 'ElasticSearch';
requires 'Encode', '2.51';
requires 'Exporter';
requires 'File::Find::Rule::Perl';
requires 'File::Path';
requires 'Gravatar::URL';
requires 'HTML::Restrict', '2.1.8';
requires 'HTML::Tree';
requires 'HTTP::Message::PSGI';
requires 'HTTP::Request';
requires 'HTTP::Request::Common';
requires 'Hash::AsObject';
requires 'Hash::Merge';
requires 'JSON';
requires 'JSON::XS';
requires 'List::MoreUtils';
requires 'List::Util';
requires 'Moose';
requires 'Moose::Role';
requires 'MooseX::ClassAttribute';
requires 'MooseX::Role::Parameterized', '1.02';
requires 'Perl::PrereqScanner','1.014';
requires 'PerlIO::gzip';
requires 'Plack::Middleware::Assets';
requires 'Plack::Middleware::ReverseProxy';
requires 'Plack::Middleware::Runtime';
requires 'Plack::Middleware::ServerStatus::Lite';
requires 'Plack::Middleware::Session';
requires 'Plack::Middleware::Session::Cookie';
requires 'Plack::Response';
requires 'Plack::Session';
requires 'Plack::Test';
requires 'Regexp::Common';
requires 'Regexp::Common';
requires 'Regexp::Common::time';
requires 'Regexp::Common::time';
requires 'Template::Alloy';
requires 'Template::Plugin::DateTime';
requires 'Template::Plugin::JSON';
requires 'Template::Plugin::Markdown';
requires 'Template::Plugin::Number::Format';
requires 'Template::Plugin::Page';
requires 'Template::Plugins';
requires 'Test::MockObject','1.09';
requires 'Test::More', '0.96';
requires 'Test::XPath', '0.15';
requires 'Try::Tiny', '0.09';
requires 'URI';
requires 'XML::Feed';
requires 'XML::Simple';
requires 'mro';
requires 'namespace::autoclean';
requires 'overload';
requires 'utf8';
requires 'version', '0.77';
