services:
  web-asset-build:
    build:
      context: .
      target: build-assets
    volumes:
      - './root/static/:/build/root/static/'
      - 'web-assets:/build/root/assets/'
    command: ['./build-assets.mjs', '--watch']
    develop:
      watch:
        - path: ./build-assets.mjs
          action: rebuild
        - path: ./package.json
          action: rebuild
  web-server:
    build:
      context: .
      target: develop
    volumes:
      - './:/app/'
      - 'web-assets:/app/root/assets/'
      - '/app/local'
    ports:
      - '5001:8000'
    environment:
      # default is 120, shorten to work with compose label
      COLUMNS: 96
    depends_on:
      - web-asset-build
    develop:
      watch:
        - path: ./cpanfile
          action: rebuild
  test:
    profiles:
      - test
    build:
      context: .
      target: test
    volumes:
      - './:/app/'
      - 'web-assets:/app/root/assets/'
      - '/app/local'
      - '/app/node_modules'
      - '${GIT_COMMON_DIR:-/dev/null}:${GIT_COMMON_DIR:-/dev/null}:ro'
    environment:
      COLUMNS: 96
    init: true
    stdin_open: true
    tty: true
    depends_on:
      - web-asset-build
    command: ['prove', '-lvr', 't']
volumes:
  web-assets:
