=head1 GETTING STARTED

Install Dist::Zilla using your preferred CPAN client:

 $ cpanm Dist::Zilla

Install the project dependencies:

 $ dzil listdeps | cpanm

Start server on port 5000

 $ twiggy lib/MetaCPAN/Web.pm

The backend defaults to C<api.metacpan.org>. Running a local API server is optional and not required to hack on the front-end.

For development based on the live API, you should run the front-end as follows:

 $ METACPAN_API=api.beta.metacpan.org twiggy lib/MetaCPAN/Web.pm -p 5001 -R lib -R templates -E development

Change METACPAN_API if you are running your own local API:

 $ METACPAN_API=localhost:5000 twiggy lib/MetaCPAN/Web.pm -p 5001 -R lib -R templates -E development
 
This will use the API server at C<localhost:5000> and sets the port of the front-end to 5001.
The process will watch changes in the current directory and start with the
L<Twiggy> server.
