#!/bin/bash

while [[ $# -gt 0 ]]; do
    case "$1" in
        --suffix)
            METACPAN_WEB_CONFIG_LOCAL_SUFFIX="$2"
            export METACPAN_WEB_CONFIG_LOCAL_SUFFIX
            shift
        ;;
        --suffix=*)
            METACPAN_WEB_CONFIG_LOCAL_SUFFIX="${1:9}"
            export METACPAN_WEB_CONFIG_LOCAL_SUFFIX
        ;;
        *)
            echo "Unsupported option $1" >&2
            exit 1
        ;;
    esac
    shift
done

export METACPAN_WEB_PORT=5001
export PLACK_ENV=development
export COLUMNS="$(tput cols)"

suffix="$METACPAN_WEB_CONFIG_LOCAL_SUFFIX"
[ -z "$suffix" ] && suffix="local"

log4perl="$(perl -MConfig::ZOMG -e'print Config::ZOMG->new(name => "MetaCPAN::Web")->load->{log4perl_file}')"
[ -z "$log4perl" ] && log4perl="log4perl.conf"

plackup -r -R metacpan_web.conf -R "metacpan_web_$suffix.conf" -R "$log4perl" -o localhost -p "$METACPAN_WEB_PORT" &
app_pid="$!"
trap 'kill "$app_pid"; exit 1' SIGHUP SIGINT SIGTERM SIGQUIT
while true; do
    sleep 1
    ( echo '' >/dev/tcp/localhost/"$METACPAN_WEB_PORT" ) 2>/dev/null && break
done
for fast_handler in Feersum Gazelle Starlet Starman; do
    perl -mPlack::Handler::$fast_handler -e1 &>/dev/null && break
done
plackup --no-default-middleware -s "$fast_handler" -o localhost -p 5000 static-app.psgi
kill "$app_pid"
